### ISSUE TITLE
"The functions createReadStream and createWriteStream pass the streams it to their completion callback instead of returning it"

### ISSUE THREAD

**Issue by timoxley** [adaltas/node-ssh2-fs#2]
> The functions createReadStream and createWriteStream pass the streams it to their completion callback instead of returning it.

You could just return a stream that acts as a buffer until the connection is ready then once it's set up, it simply becomes a passthrough stream. It just holds pipes and writes until the real stream is ready.

The hooks system in reduplexer helps you do this:
https://github.com/mcollina/reduplexer

**Comment by wdavidw** [comment]
Closing, this has been implemented since then.
