### ISSUE TITLE
Can't exist Nodejs Script without CTRL-C

### ISSUE THREAD

**Issue by mesobius** [adaltas/node-ssh2-fs#5]
Hi, 
probably not a real issue, but I don't understand why ...

my js script : 

```
connect = require('ssh2-connect');
fs = require('ssh2-fs');
connect({host: 'myaddressIp',
  port: 22,
  username: 'my username',
  passphrase : 'my passphrase',
  privateKey: require('fs').readFileSync('mykey')}, function(err, ssh){
  fs.readdir(ssh,'.', function (err, stdout, stderr){
    console.log(stdout);
  });
  fs.writeFile(ssh,'./file2.txt',"new data to write", function (err, stdout, stderr){
    console.log(stdout);
  });
});
```

when I run "node myscript.js", the script do the job, but it never exit to the prompt line.
I need to do a CTRL-C to exit my script.

Is it an issue or what do I need to exit correctly of my script.
Thanks a lot for your response.

Req

**Comment by wdavidw** [comment]
Seems normal, you need to close the ssh connection with `ssh.close()` once you're done.

**Comment by mesobius** [comment]
Ah OK !
I haven't seen and understand this point.
Sorry to have posted this fault issue.
And thanks for your quick answer ;)
